apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.103
  ports:
    - port: 5050
      targetPort: 5050
      name: wordpress
  selector:
    app: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      name: wordpress
      labels:
        app: wordpress
    spec:
      containers:
      - image: wp_service
        name: wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
