apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
spec:
  selector:
    app: ftps
  loadBalancerIP: 192.168.99.221
  type: LoadBalancer
  ports:
  - port: 21
    name: main-control
  - port: 21000
    name: passive-mode
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  template:
    metadata:
      name: ftps-pod
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps-container
        image: ftps_service
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: main-control
        - containerPort: 21000
          name: passive-mode

