apiVersion: v1
kind: Service
metadata:
  name: php-service
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.221
  ports:
    - port: 5000
      name: http
      protocol: TCP
      targetPort: 5000
  selector:
    app: phpmyadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin-container
          image: php_service
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
